# Generated by Django 2.1 on 2018-08-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
