# Generated by Django 2.1 on 2018-08-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballon', '0002_auto_20180827_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=800)),
                ('city', models.CharField(max_length=800)),
                ('state', models.CharField(max_length=800)),
                ('zip_code', models.FloatField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=800)),
                ('degree', models.CharField(max_length=800)),
                ('graduted', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=800)),
                ('category', models.CharField(max_length=800)),
                ('tags', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('url', models.URLField(verbose_name='')),
                ('modal', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('url', models.URLField(verbose_name='')),
                ('className', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800)),
                ('user', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=800)),
                ('title', models.CharField(max_length=800)),
                ('years', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': 'Work',
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
    ]
