# Generated by Django 2.1 on 2018-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballon', '0005_auto_20180828_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
