# Generated by Django 2.1 on 2018-08-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballon', '0003_auto_20180828_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='ballon.Education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ballon.Main'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(to='ballon.Project'),
        ),
        migrations.AddField(
            model_name='resume',
            name='social',
            field=models.ManyToManyField(to='ballon.Social'),
        ),
        migrations.AddField(
            model_name='resume',
            name='testimonials',
            field=models.ManyToManyField(to='ballon.Testimonial'),
        ),
        migrations.AddField(
            model_name='resume',
            name='works',
            field=models.ManyToManyField(to='ballon.Work'),
        ),
    ]
